// Correctness tests for the 2-D tensor-product B-spline evaluator
// (include/CoolProp/spline/TensorBSpline2D.h).
//
// The reference values in the "matches scipy" cases were generated by
// dev/scripts/gen_tensor_bspline_ref.py using scipy.interpolate.BSpline.
// Re-run that script to regenerate them if the fixture changes.

#include "CoolProp/Exceptions.h"
#include "CoolProp/spline/TensorBSpline2D.h"

#if defined(ENABLE_CATCH)
#    include <catch2/catch_all.hpp>

#    include <cstddef>
#    include <cmath>
#    include <limits>
#    include <vector>

namespace cp_spline = CoolProp::spline;

namespace {
// Shared fixture.  DIFFERENT order per axis on purpose, so a bug that
// swaps or conflates the two axes cannot pass, and non-uniform interior
// knots so the interval search is genuinely exercised.
//
// order 4 (cubic) in x with interior knots at 0.3, 0.7  -> nx = 6
// order 3 (quadratic) in y with interior knots at 1.5, 2.2 -> ny = 5
const std::vector<double> kx{0.0, 0.0, 0.0, 0.0, 0.3, 0.7, 1.0, 1.0, 1.0, 1.0};
const std::vector<double> ky{0.0, 0.0, 0.0, 1.5, 2.2, 4.0, 4.0, 4.0};
constexpr std::size_t kOx = 4;
constexpr std::size_t kOy = 3;
constexpr std::size_t kNx = 6;
constexpr std::size_t kNy = 5;
}  // namespace

TEST_CASE("TensorBSpline2D reproduces a constant (partition of unity)", "[TensorBSpline][spline]") {
    // With every coefficient equal to 1, sum_i B_i(x) = sum_j B_j(y) = 1
    // gives f == 1 identically.  This pins down basis normalisation and
    // the interval search independently of any reference data.
    const std::vector<double> coefs(kNx * kNy, 1.0);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);

    for (const double x : {0.0, 0.05, 0.3, 0.42, 0.7, 0.93, 1.0}) {
        for (const double y : {0.0, 0.4, 1.5, 2.2, 3.3, 4.0}) {
            REQUIRE_THAT(sp.eval(x, y), Catch::Matchers::WithinAbs(1.0, 1e-14));
        }
    }
}

TEST_CASE("TensorBSpline2D value and all five partials match scipy", "[TensorBSpline][spline]") {
    // Generated by dev/scripts/gen_tensor_bspline_ref.py.
    const std::vector<double> coefs{2.025520, 1.954294, 0.658115, 1.753859,  2.829673,  -1.233570, -0.159747, -2.192532, 2.309879,  0.440626,
                                    0.045353, 2.551193, 2.269414, -2.300840, -0.677777, -1.798898, -0.031139, 2.561153,  -0.798349, 0.615241,
                                    0.885038, 1.357357, 1.225375, 2.449620,  -2.912570, 0.760539,  -1.743761, -1.785901, 0.132857,  -0.181576};
    REQUIRE(coefs.size() == kNx * kNy);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);

    // {x, y, f, f_x, f_y, f_xx, f_yy, f_xy} from scipy.interpolate.BSpline.
    // Probes include x exactly on an interior knot (0.30), y exactly on an
    // interior knot (2.20), and both domain corners, because those are
    // where an off-by-one in the span search shows up.
    const double ref[][8] = {
      {0.15, 0.90, 0.16402259079730985, 1.2613275639981432, -0.12239174108534327, 98.832328766728523, -2.0167728971243042, 5.6352068406307954},
      {0.30, 2.20, 0.44337809281632634, 5.5169224138775483, -1.1616664228571429, -18.123368669387752, 0.9267175654824894, -16.529672228571425},
      {0.55, 3.10, -0.23106427391964296, 2.5469436464540829, -0.8281866451162132, 12.602091205102033, 2.0261004911407152, -1.6600174824829943},
      {0.92, 1.20, 0.10338821319427244, -15.479292226560133, -0.076203717548572622, -145.35325240526075, 0.59913204222459893, -8.0494601290136742},
      {0.00, 0.00, 2.0255200000000002, -32.590900000000005, -0.094968000000000607, 253.81332380952384, -0.72225103030302984, 15.267320000000002},
      {1.00, 4.00, -0.18157599999999999, 27.309939999999994, -0.34937000000000001, 282.8608666666666, -1.046875777777778, 56.086188888888884},
    };

    for (const auto& r : ref) {
        const double x = r[0];
        const double y = r[1];
        INFO("at x = " << x << ", y = " << y);
        // Each partial is checked separately so a single wrong derivative
        // order is attributable rather than hidden in an aggregate.
        CHECK_THAT(sp.eval(x, y, 0, 0), Catch::Matchers::WithinRel(r[2], 1e-12));
        CHECK_THAT(sp.eval(x, y, 1, 0), Catch::Matchers::WithinRel(r[3], 1e-12));
        CHECK_THAT(sp.eval(x, y, 0, 1), Catch::Matchers::WithinRel(r[4], 1e-12));
        CHECK_THAT(sp.eval(x, y, 2, 0), Catch::Matchers::WithinRel(r[5], 1e-12));
        CHECK_THAT(sp.eval(x, y, 0, 2), Catch::Matchers::WithinRel(r[6], 1e-12));
        CHECK_THAT(sp.eval(x, y, 1, 1), Catch::Matchers::WithinRel(r[7], 1e-12));
    }
}

TEST_CASE("TensorBSpline2D throws rather than failing open outside its domain", "[TensorBSpline][spline][nan]") {
    // The reference MATLAB/scipy behaviour is to return NaN out of
    // domain.  A NaN that reaches a thermodynamic property is far worse
    // than an exception -- it propagates silently through arithmetic and
    // surfaces as a wrong answer somewhere unrelated.  Throw instead.
    const std::vector<double> coefs(kNx * kNy, 1.0);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);

    SECTION("each of the four directions") {
        CHECK_THROWS_AS(sp.eval(-1e-6, 2.0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(1.0 + 1e-6, 2.0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, -1e-6), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, 4.0 + 1e-6), CoolProp::ValueError);
    }
    SECTION("non-finite inputs cannot sneak past the comparisons") {
        const double nan = std::numeric_limits<double>::quiet_NaN();
        const double inf = std::numeric_limits<double>::infinity();
        CHECK_THROWS_AS(sp.eval(nan, 2.0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, nan), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(inf, 2.0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, -inf), CoolProp::ValueError);
    }
    SECTION("derivative requests are guarded too, not just the value") {
        CHECK_THROWS_AS(sp.eval(-1e-6, 2.0, 1, 0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, 5.0, 0, 2), CoolProp::ValueError);
    }
}

TEST_CASE("TensorBSpline2D validates its inputs in the public constructor", "[TensorBSpline][spline][validation]") {
    // Validation lives in the constructor, not in a factory, so there is
    // no way to obtain an unchecked instance.
    //
    // These assert on the MESSAGE, not just the type.  Every guard throws
    // ValueError, so CHECK_THROWS_AS alone lets a section pass on the wrong
    // guard -- mutation testing showed deleting the knot-count check still
    // passed, because the coefficient-count check threw instead.
    const std::vector<double> good(kNx * kNy, 1.0);

    SECTION("a well-formed surface constructs (positive control)") {
        // Without this, a constructor that threw unconditionally would
        // satisfy every other section here.
        CHECK_NOTHROW(cp_spline::TensorBSpline2D(kx, ky, kOx, kOy, good));
    }
    SECTION("coefficient count must match the knots and orders") {
        std::vector<double> short_coefs(kNx * kNy - 1, 1.0);
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(kx, ky, kOx, kOy, short_coefs), Catch::Matchers::ContainsSubstring("coefficients, got"));
        std::vector<double> long_coefs(kNx * kNy + 1, 1.0);
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(kx, ky, kOx, kOy, long_coefs), Catch::Matchers::ContainsSubstring("coefficients, got"));
    }
    SECTION("knot vectors must be non-decreasing") {
        std::vector<double> bad = kx;
        bad[4] = 0.8;  // now 0.8 sits before 0.7
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(bad, ky, kOx, kOy, good), Catch::Matchers::ContainsSubstring("non-decreasing"));
        std::vector<double> bad_y = ky;
        bad_y[3] = 3.0;  // now 3.0 sits before 2.2
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(kx, bad_y, kOx, kOy, good), Catch::Matchers::ContainsSubstring("non-decreasing"));
    }
    SECTION("order zero is rejected rather than underflowing to a huge degree") {
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(kx, ky, 0, kOy, good), Catch::Matchers::ContainsSubstring("order must be at least 1"));
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(kx, ky, kOx, 0, good), Catch::Matchers::ContainsSubstring("order must be at least 1"));
    }
    SECTION("order above kMaxOrder is rejected rather than overrunning the stack scratch") {
        const std::size_t too_big = cp_spline::TensorBSpline2D::kMaxOrder + 1;
        std::vector<double> knots(too_big + 2, 0.0);
        for (std::size_t i = 0; i < knots.size(); ++i) {
            knots[i] = static_cast<double>(i);
        }
        std::vector<double> c(2 * kNy, 1.0);
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(knots, ky, too_big, kOy, c), Catch::Matchers::ContainsSubstring("exceeds kMaxOrder"));
    }
    SECTION("too few knots for the requested order is rejected, not wrapped around") {
        // knots.size() <= order would make n = size - order underflow.
        const std::vector<double> tiny{0.0, 1.0};
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(tiny, ky, kOx, kOy, good), Catch::Matchers::ContainsSubstring("needs at least"));
    }
    SECTION("non-finite knots are rejected") {
        std::vector<double> bad = kx;
        bad[5] = std::numeric_limits<double>::quiet_NaN();
        CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(bad, ky, kOx, kOy, good), Catch::Matchers::ContainsSubstring("non-finite"));
    }
}

TEST_CASE("TensorBSpline2D handles repeated interior knots", "[TensorBSpline][spline][multiplicity]") {
    // An interior knot of multiplicity 2.  NOTE: contrary to what an
    // earlier version of this comment claimed, the bisection in find_span
    // provably cannot return a zero-width span -- its exit condition
    // requires knots[mid] <= v < knots[mid+1].  The only path that can
    // reach one is the v >= knots[n] early return, which is covered by
    // the run-length rejection tested below.  What this case does cover
    // is a knot vector whose interior multiplicity is > 1 but still
    // within the order, which the main fixture does not have.
    const std::vector<double> kxm{0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0};
    const std::vector<double> kym{0.0, 0.0, 0.0, 2.0, 4.0, 4.0, 4.0};
    const std::vector<double> cm{0.500382, 1.588855,  1.102743,  -1.099171, -0.799335, 1.494214,  -1.978939, 1.284914,
                                 1.188278, -0.128260, -0.787870, -0.886298, -0.980522, -0.219695, 0.018193,  0.213989,
                                 1.982001, 1.170648,  0.488717,  1.955841,  -1.138765, -1.359152, 0.450158,  -1.824232};
    const cp_spline::TensorBSpline2D sp(kxm, kym, 4, 3, cm);

    // {x, y, f, f_x, f_y}
    const double ref[][5] = {
      {0.25, 1.00, 0.36755239062500006, -2.6326550625000005, -0.17537378124999997},
      {0.50, 2.00, -0.27940799999999999, 1.071942, -0.10543049999999998},
      {0.75, 3.00, 0.28044037499999996, 1.3575600000000001, 0.18101337500000003},
      {0.50, 4.00, -0.33615450000000002, 3.3008610000000003, 0.04868399999999995},
    };
    for (const auto& r : ref) {
        INFO("at x = " << r[0] << ", y = " << r[1]);
        CHECK_THAT(sp.eval(r[0], r[1]), Catch::Matchers::WithinRel(r[2], 1e-12));
        CHECK_THAT(sp.eval(r[0], r[1], 1, 0), Catch::Matchers::WithinRel(r[3], 1e-12));
        CHECK_THAT(sp.eval(r[0], r[1], 0, 1), Catch::Matchers::WithinRel(r[4], 1e-12));
    }
}

TEST_CASE("TensorBSpline2D returns zero for derivatives above the degree", "[TensorBSpline][spline]") {
    // y has order 3, i.e. degree 2, so the third y-derivative and beyond
    // vanish identically.  Guards the early-out in basis_ders.
    const std::vector<double> coefs(kNx * kNy, 1.0);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);
    CHECK_THAT(sp.eval(0.42, 2.7, 0, 3), Catch::Matchers::WithinAbs(0.0, 1e-14));
    CHECK_THAT(sp.eval(0.42, 2.7, 0, 7), Catch::Matchers::WithinAbs(0.0, 1e-14));
    CHECK_THAT(sp.eval(0.42, 2.7, 4, 0), Catch::Matchers::WithinAbs(0.0, 1e-14));
}

TEST_CASE("TensorBSpline2D requires at least `order` coefficients per axis", "[TensorBSpline][spline][validation]") {
    // n = knots.size() - order must be >= order.  When n < order, find_span's
    // right-endpoint early return yields a span below p, and eval's
    // `sx - px + a` then wraps in std::size_t.  Verified pre-fix under ASAN as
    // a heap-buffer-overflow READ at the eval() coefficient lookup.
    //
    // The degenerate case is n == order - 1, where the domain
    // [knots[order-1], knots[n]] collapses to a single point that
    // check_in_domain is then GUARANTEED to admit -- so the guard in front of
    // the bisection cannot save us here.  It has to be refused at construction.
    const std::vector<double> kx_short{0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0};  // 7 knots, order 4 -> n = 3
    const std::vector<double> ky_ok{0.0, 0.0, 0.0, 1.0, 1.0, 1.0};          // 6 knots, order 3 -> n = 3
    CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(kx_short, ky_ok, 4, 3, std::vector<double>(9, 1.0)),
                      Catch::Matchers::ContainsSubstring("needs at least"));
    CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(ky_ok, kx_short, 3, 4, std::vector<double>(9, 1.0)),
                      Catch::Matchers::ContainsSubstring("needs at least"));

    // The boundary must stay open: n == order exactly is legitimate.
    const std::vector<double> kx_min{0.0, 0.0, 0.0, 1.0, 1.0, 1.0};  // 6 knots, order 3 -> n = 3 == order
    CHECK_NOTHROW(cp_spline::TensorBSpline2D(kx_min, kx_min, 3, 3, std::vector<double>(9, 1.0)));
}

TEST_CASE("TensorBSpline2D rejects knot multiplicity above the order", "[TensorBSpline][spline][validation]") {
    // A run of equal knots longer than `order` makes the Cox-de Boor
    // denominator exactly zero on the span the right-endpoint early return
    // selects, so eval RETURNED NaN rather than throwing -- the precise
    // fail-open this class exists to prevent.  Refuse it at construction.
    const std::vector<double> bad{0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0};  // run of 1.0 has length 4 > order 3
    const std::vector<double> ok{0.0, 0.0, 0.0, 1.0, 1.0, 1.0};
    CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(bad, ok, 3, 3, std::vector<double>(std::size_t{4} * 3, 1.0)),
                      Catch::Matchers::ContainsSubstring("knot multiplicity"));
    CHECK_THROWS_WITH(cp_spline::TensorBSpline2D(ok, bad, 3, 3, std::vector<double>(std::size_t{3} * 4, 1.0)),
                      Catch::Matchers::ContainsSubstring("knot multiplicity"));

    // Multiplicity exactly == order is the normal clamped case and must pass.
    CHECK_NOTHROW(cp_spline::TensorBSpline2D(ok, ok, 3, 3, std::vector<double>(9, 1.0)));
}

TEST_CASE("TensorBSpline2D never returns a non-finite value on a valid surface", "[TensorBSpline][spline][nan]") {
    // COO-45 requires "assert not NaN".  The existing coverage only asserted
    // that the THROW paths throw; nothing checked that the success path is
    // finite.  Sweep the domain, including both endpoints and the knots.
    const std::vector<double> coefs(kNx * kNy, 1.0);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);
    const unsigned orders[][2] = {{0, 0}, {1, 0}, {0, 1}, {2, 0}, {0, 2}, {1, 1}};
    for (int i = 0; i <= 20; ++i) {
        const double x = static_cast<double>(i) / 20.0;
        for (int j = 0; j <= 20; ++j) {
            const double y = 4.0 * static_cast<double>(j) / 20.0;
            for (const auto& d : orders) {
                const double v = sp.eval(x, y, d[0], d[1]);
                INFO("x = " << x << ", y = " << y << ", d = (" << d[0] << "," << d[1] << ")");
                REQUIRE(std::isfinite(v));
            }
        }
    }
}

TEST_CASE("TensorBSpline2D derivative order is range-checked before narrowing", "[TensorBSpline][spline][validation]") {
    // `static_cast<int>(nd)` turns nd >= 2^31 negative, which slipped past the
    // `k_want > p` early-out and indexed ders[-1].  Confirmed pre-fix under
    // UBSAN as "index -1 out of bounds for type 'double[16][16]'".
    //
    // Pre-fix this read uninitialised stack, so the assertion below could pass
    // by luck; the UBSAN trace, not this test, is the evidence that it was
    // broken.  Post-fix the result is deterministic and this guards it.
    const std::vector<double> coefs(kNx * kNy, 1.0);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);
    for (const unsigned nd : {20u, 100u, 0x7FFFFFFFu, 0x80000000u, 0xFFFFFFFFu}) {
        INFO("nd = " << nd);
        const double dy = sp.eval(0.42, 2.7, 0, nd);
        const double dx = sp.eval(0.42, 2.7, nd, 0);
        REQUIRE(std::isfinite(dy));
        REQUIRE(std::isfinite(dx));
        CHECK_THAT(dy, Catch::Matchers::WithinAbs(0.0, 1e-14));
        CHECK_THAT(dx, Catch::Matchers::WithinAbs(0.0, 1e-14));
    }
}

TEST_CASE("TensorBSpline2D high-order derivatives do not overflow the scale factor", "[TensorBSpline][spline]") {
    // The falling-factorial scaling p*(p-1)*... exceeds 2^31 at order 15, so
    // accumulating it in `int` silently returned wrong derivatives across part
    // of the range kMaxOrder advertises.  Reference from scipy.
    const std::vector<double> highorder_kx{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
    const std::vector<double> highorder_ky{0, 0, 1, 1};
    const std::vector<double> highorder_c{0.729595,  0.710605, 0.622047,  -0.477107, -0.845601, 0.892932,  0.227583,  -0.994738, 0.820814, 0.969607,
                                          -0.427407, 0.627322, -0.835184, -0.123440, 0.635408,  -0.182533, 0.035499,  -0.765920, 0.628013, -0.004265,
                                          -0.503442, 0.553372, 0.958457,  0.076686,  0.474300,  0.985521,  -0.939745, 0.197955,  0.934591, -0.765327};
    const cp_spline::TensorBSpline2D sp(highorder_kx, highorder_ky, 15, 2, highorder_c);
    // {x, y, d00, d10_0, d12_0, d14_0}
    const double ref[][6] = {
      {0.3, 0.5, 0.10790408280695911, 71934819558.937683, 3045415990388.0981, -278259267961772.72},
      {0.7, 0.25, 0.21663003118109, -11773121881.499836, -10597773524988.631, -362545500906504.19},
    };
    for (const auto& r : ref) {
        INFO("at x = " << r[0] << ", y = " << r[1]);
        CHECK_THAT(sp.eval(r[0], r[1], 0, 0), Catch::Matchers::WithinRel(r[2], 1e-11));
        CHECK_THAT(sp.eval(r[0], r[1], 10, 0), Catch::Matchers::WithinRel(r[3], 1e-11));
        CHECK_THAT(sp.eval(r[0], r[1], 12, 0), Catch::Matchers::WithinRel(r[4], 1e-11));
        CHECK_THAT(sp.eval(r[0], r[1], 14, 0), Catch::Matchers::WithinRel(r[5], 1e-11));
    }
}

TEST_CASE("TensorBSpline2D uses the true support interval on unclamped knots", "[TensorBSpline][spline]") {
    // For an unclamped knot vector the support is [knots[order-1], knots[n]],
    // strictly inside the knot vector.  On a clamped vector that coincides
    // with [knots.front(), knots.back()], so nothing else here would notice
    // check_in_domain using the wrong bounds.
    const std::vector<double> ukx{0, 1, 2, 3, 4, 5, 6, 7, 8, 9};  // order 4 -> n = 6, support [3, 6]
    const std::vector<double> uky{0, 1, 2, 3, 4, 5, 6, 7};        // order 3 -> n = 5, support [2, 5]
    const std::vector<double> uc{-1.485719, -0.002889, 0.405993, -1.885244, -1.408296, 1.712844, -1.718318, -1.480904, 1.793314, 0.487534,
                                 -0.524028, 0.045560,  0.651372, -0.898765, -1.448128, 1.152158, 0.681442,  0.049529,  1.266946, 0.196301,
                                 1.923655,  -1.181962, 0.214921, -0.065501, -0.586901, 0.366381, -1.058795, 1.208811,  1.469334, -1.484961};
    const cp_spline::TensorBSpline2D sp(ukx, uky, 4, 3, uc);

    // {x, y, f, f_x, f_y}
    const double ref[][5] = {
      {3.0, 2.0, -0.16574766666666663, 0.25253500000000001, -1.9453716666666665},
      {4.25, 3.5, 0.24472814257812497, 0.33897408593750006, -0.071796700520833368},
      {5.5, 4.0, 0.37652434374999993, -0.18185856249999999, 0.4221098124999999},
      {6.0, 5.0, -0.096832333333333381, -0.36971850000000001, -1.0184233333333332},
    };
    for (const auto& r : ref) {
        INFO("at x = " << r[0] << ", y = " << r[1]);
        CHECK_THAT(sp.eval(r[0], r[1]), Catch::Matchers::WithinRel(r[2], 1e-12));
        CHECK_THAT(sp.eval(r[0], r[1], 1, 0), Catch::Matchers::WithinRel(r[3], 1e-12));
        CHECK_THAT(sp.eval(r[0], r[1], 0, 1), Catch::Matchers::WithinRel(r[4], 1e-12));
    }
    // Outside the SUPPORT but still inside the knot vector: must be refused.
    CHECK_THROWS_AS(sp.eval(2.5, 3.0), CoolProp::ValueError);  // x < knots[3]
    CHECK_THROWS_AS(sp.eval(6.5, 3.0), CoolProp::ValueError);  // x > knots[6]
    CHECK_THROWS_AS(sp.eval(4.0, 1.5), CoolProp::ValueError);  // y < knots[2]
    CHECK_THROWS_AS(sp.eval(4.0, 5.5), CoolProp::ValueError);  // y > knots[5]
}
#endif
