// Correctness tests for the 2-D tensor-product B-spline evaluator
// (include/CoolProp/spline/TensorBSpline2D.h).
//
// The reference values in the "matches scipy" cases were generated by
// dev/scripts/gen_tensor_bspline_ref.py using scipy.interpolate.BSpline.
// Re-run that script to regenerate them if the fixture changes.

#include "CoolProp/Exceptions.h"
#include "CoolProp/spline/TensorBSpline2D.h"

#if defined(ENABLE_CATCH)
#    include <catch2/catch_all.hpp>

#    include <cmath>
#    include <limits>
#    include <vector>

namespace cp_spline = CoolProp::spline;

namespace {
// Shared fixture.  DIFFERENT order per axis on purpose, so a bug that
// swaps or conflates the two axes cannot pass, and non-uniform interior
// knots so the interval search is genuinely exercised.
//
// order 4 (cubic) in x with interior knots at 0.3, 0.7  -> nx = 6
// order 3 (quadratic) in y with interior knots at 1.5, 2.2 -> ny = 5
const std::vector<double> kx{0.0, 0.0, 0.0, 0.0, 0.3, 0.7, 1.0, 1.0, 1.0, 1.0};
const std::vector<double> ky{0.0, 0.0, 0.0, 1.5, 2.2, 4.0, 4.0, 4.0};
constexpr std::size_t kOx = 4;
constexpr std::size_t kOy = 3;
constexpr std::size_t kNx = 6;
constexpr std::size_t kNy = 5;
}  // namespace

TEST_CASE("TensorBSpline2D reproduces a constant (partition of unity)", "[TensorBSpline][spline]") {
    // With every coefficient equal to 1, sum_i B_i(x) = sum_j B_j(y) = 1
    // gives f == 1 identically.  This pins down basis normalisation and
    // the interval search independently of any reference data.
    const std::vector<double> coefs(kNx * kNy, 1.0);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);

    for (const double x : {0.0, 0.05, 0.3, 0.42, 0.7, 0.93, 1.0}) {
        for (const double y : {0.0, 0.4, 1.5, 2.2, 3.3, 4.0}) {
            REQUIRE_THAT(sp.eval(x, y), Catch::Matchers::WithinAbs(1.0, 1e-14));
        }
    }
}

TEST_CASE("TensorBSpline2D value and all five partials match scipy", "[TensorBSpline][spline]") {
    // Generated by dev/scripts/gen_tensor_bspline_ref.py.
    const std::vector<double> coefs{2.025520, 1.954294, 0.658115, 1.753859,  2.829673,  -1.233570, -0.159747, -2.192532, 2.309879,  0.440626,
                                    0.045353, 2.551193, 2.269414, -2.300840, -0.677777, -1.798898, -0.031139, 2.561153,  -0.798349, 0.615241,
                                    0.885038, 1.357357, 1.225375, 2.449620,  -2.912570, 0.760539,  -1.743761, -1.785901, 0.132857,  -0.181576};
    REQUIRE(coefs.size() == kNx * kNy);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);

    // {x, y, f, f_x, f_y, f_xx, f_yy, f_xy} from scipy.interpolate.BSpline.
    // Probes include x exactly on an interior knot (0.30), y exactly on an
    // interior knot (2.20), and both domain corners, because those are
    // where an off-by-one in the span search shows up.
    const double ref[][8] = {
      {0.15, 0.90, 0.16402259079730985, 1.2613275639981432, -0.12239174108534327, 98.832328766728523, -2.0167728971243042, 5.6352068406307954},
      {0.30, 2.20, 0.44337809281632634, 5.5169224138775483, -1.1616664228571429, -18.123368669387752, 0.9267175654824894, -16.529672228571425},
      {0.55, 3.10, -0.23106427391964296, 2.5469436464540829, -0.8281866451162132, 12.602091205102033, 2.0261004911407152, -1.6600174824829943},
      {0.92, 1.20, 0.10338821319427244, -15.479292226560133, -0.076203717548572622, -145.35325240526075, 0.59913204222459893, -8.0494601290136742},
      {0.00, 0.00, 2.0255200000000002, -32.590900000000005, -0.094968000000000607, 253.81332380952384, -0.72225103030302984, 15.267320000000002},
      {1.00, 4.00, -0.18157599999999999, 27.309939999999994, -0.34937000000000001, 282.8608666666666, -1.046875777777778, 56.086188888888884},
    };

    for (const auto& r : ref) {
        const double x = r[0];
        const double y = r[1];
        INFO("at x = " << x << ", y = " << y);
        // Each partial is checked separately so a single wrong derivative
        // order is attributable rather than hidden in an aggregate.
        CHECK_THAT(sp.eval(x, y, 0, 0), Catch::Matchers::WithinRel(r[2], 1e-12));
        CHECK_THAT(sp.eval(x, y, 1, 0), Catch::Matchers::WithinRel(r[3], 1e-12));
        CHECK_THAT(sp.eval(x, y, 0, 1), Catch::Matchers::WithinRel(r[4], 1e-12));
        CHECK_THAT(sp.eval(x, y, 2, 0), Catch::Matchers::WithinRel(r[5], 1e-12));
        CHECK_THAT(sp.eval(x, y, 0, 2), Catch::Matchers::WithinRel(r[6], 1e-12));
        CHECK_THAT(sp.eval(x, y, 1, 1), Catch::Matchers::WithinRel(r[7], 1e-12));
    }
}

TEST_CASE("TensorBSpline2D throws rather than failing open outside its domain", "[TensorBSpline][spline][nan]") {
    // The reference MATLAB/scipy behaviour is to return NaN out of
    // domain.  A NaN that reaches a thermodynamic property is far worse
    // than an exception -- it propagates silently through arithmetic and
    // surfaces as a wrong answer somewhere unrelated.  Throw instead.
    const std::vector<double> coefs(kNx * kNy, 1.0);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);

    SECTION("each of the four directions") {
        CHECK_THROWS_AS(sp.eval(-1e-6, 2.0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(1.0 + 1e-6, 2.0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, -1e-6), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, 4.0 + 1e-6), CoolProp::ValueError);
    }
    SECTION("non-finite inputs cannot sneak past the comparisons") {
        const double nan = std::numeric_limits<double>::quiet_NaN();
        const double inf = std::numeric_limits<double>::infinity();
        CHECK_THROWS_AS(sp.eval(nan, 2.0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, nan), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(inf, 2.0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, -inf), CoolProp::ValueError);
    }
    SECTION("derivative requests are guarded too, not just the value") {
        CHECK_THROWS_AS(sp.eval(-1e-6, 2.0, 1, 0), CoolProp::ValueError);
        CHECK_THROWS_AS(sp.eval(0.5, 5.0, 0, 2), CoolProp::ValueError);
    }
}

TEST_CASE("TensorBSpline2D validates its inputs in the public constructor", "[TensorBSpline][spline][validation]") {
    // Validation lives in the constructor, not in a factory, so there is
    // no way to obtain an unchecked instance.
    const std::vector<double> good(kNx * kNy, 1.0);

    SECTION("a well-formed surface constructs (positive control)") {
        // Without this, a constructor that threw unconditionally would
        // satisfy every other section here.
        CHECK_NOTHROW(cp_spline::TensorBSpline2D(kx, ky, kOx, kOy, good));
    }
    SECTION("coefficient count must match the knots and orders") {
        std::vector<double> short_coefs(kNx * kNy - 1, 1.0);
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(kx, ky, kOx, kOy, short_coefs), CoolProp::ValueError);
        std::vector<double> long_coefs(kNx * kNy + 1, 1.0);
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(kx, ky, kOx, kOy, long_coefs), CoolProp::ValueError);
    }
    SECTION("knot vectors must be non-decreasing") {
        std::vector<double> bad = kx;
        bad[4] = 0.8;  // now 0.8 sits before 0.7
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(bad, ky, kOx, kOy, good), CoolProp::ValueError);
        std::vector<double> bad_y = ky;
        bad_y[3] = 3.0;  // now 3.0 sits before 2.2
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(kx, bad_y, kOx, kOy, good), CoolProp::ValueError);
    }
    SECTION("order zero is rejected rather than underflowing to a huge degree") {
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(kx, ky, 0, kOy, good), CoolProp::ValueError);
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(kx, ky, kOx, 0, good), CoolProp::ValueError);
    }
    SECTION("order above kMaxOrder is rejected rather than overrunning the stack scratch") {
        const std::size_t too_big = cp_spline::TensorBSpline2D::kMaxOrder + 1;
        std::vector<double> knots(too_big + 2, 0.0);
        for (std::size_t i = 0; i < knots.size(); ++i) {
            knots[i] = static_cast<double>(i);
        }
        std::vector<double> c(2 * kNy, 1.0);
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(knots, ky, too_big, kOy, c), CoolProp::ValueError);
    }
    SECTION("too few knots for the requested order is rejected, not wrapped around") {
        // knots.size() <= order would make n = size - order underflow.
        const std::vector<double> tiny{0.0, 1.0};
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(tiny, ky, kOx, kOy, good), CoolProp::ValueError);
    }
    SECTION("non-finite knots are rejected") {
        std::vector<double> bad = kx;
        bad[5] = std::numeric_limits<double>::quiet_NaN();
        CHECK_THROWS_AS(cp_spline::TensorBSpline2D(bad, ky, kOx, kOy, good), CoolProp::ValueError);
    }
}

TEST_CASE("TensorBSpline2D handles repeated interior knots", "[TensorBSpline][spline][multiplicity]") {
    // An interior knot of multiplicity 2 creates a zero-width span, which
    // the bisection in find_span can land on.  The fixture above has only
    // simple interior knots, so this exercises a path nothing else does.
    const std::vector<double> kxm{0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0};
    const std::vector<double> kym{0.0, 0.0, 0.0, 2.0, 4.0, 4.0, 4.0};
    const std::vector<double> cm{0.500382, 1.588855,  1.102743,  -1.099171, -0.799335, 1.494214,  -1.978939, 1.284914,
                                 1.188278, -0.128260, -0.787870, -0.886298, -0.980522, -0.219695, 0.018193,  0.213989,
                                 1.982001, 1.170648,  0.488717,  1.955841,  -1.138765, -1.359152, 0.450158,  -1.824232};
    const cp_spline::TensorBSpline2D sp(kxm, kym, 4, 3, cm);

    // {x, y, f, f_x, f_y}
    const double ref[][5] = {
      {0.25, 1.00, 0.36755239062500006, -2.6326550625000005, -0.17537378124999997},
      {0.50, 2.00, -0.27940799999999999, 1.071942, -0.10543049999999998},
      {0.75, 3.00, 0.28044037499999996, 1.3575600000000001, 0.18101337500000003},
      {0.50, 4.00, -0.33615450000000002, 3.3008610000000003, 0.04868399999999995},
    };
    for (const auto& r : ref) {
        INFO("at x = " << r[0] << ", y = " << r[1]);
        CHECK_THAT(sp.eval(r[0], r[1]), Catch::Matchers::WithinRel(r[2], 1e-12));
        CHECK_THAT(sp.eval(r[0], r[1], 1, 0), Catch::Matchers::WithinRel(r[3], 1e-12));
        CHECK_THAT(sp.eval(r[0], r[1], 0, 1), Catch::Matchers::WithinRel(r[4], 1e-12));
    }
}

TEST_CASE("TensorBSpline2D returns zero for derivatives above the degree", "[TensorBSpline][spline]") {
    // y has order 3, i.e. degree 2, so the third y-derivative and beyond
    // vanish identically.  Guards the early-out in basis_ders.
    const std::vector<double> coefs(kNx * kNy, 1.0);
    const cp_spline::TensorBSpline2D sp(kx, ky, kOx, kOy, coefs);
    CHECK_THAT(sp.eval(0.42, 2.7, 0, 3), Catch::Matchers::WithinAbs(0.0, 1e-14));
    CHECK_THAT(sp.eval(0.42, 2.7, 0, 7), Catch::Matchers::WithinAbs(0.0, 1e-14));
    CHECK_THAT(sp.eval(0.42, 2.7, 4, 0), Catch::Matchers::WithinAbs(0.0, 1e-14));
}
#endif
