services:
  runner:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /input
        read_only: true
      - type: bind
        source: ./output
        target: /output