[General]
P = 101325

[Psychr]
virial = True
coolprop = True
refprop = False
saturationcolor = #000000
saturationlinewidth = 1.0
saturationlinestyle = -
saturationmarker = None
isotdbstart = 274.0
isotdbend = 330.0
isotdbstep = 1.0
isotdbcustom = False
isotdblist = 
isotdbcolor = #000000
isotdblinewidth = 0.5
isotdblinestyle = :
isotdbmarker = None
isotdblabel = False
isotdbunits = False
isotdbposition = 50
isowstart = 0.0
isowend = 0.04
isowstep = 0.001
isowcustom = False
isowlist = 
isowcolor = #000000
isowlinewidth = 0.5
isowlinestyle = :
isowmarker = None
isowlabel = False
isowunits = False
isowposition = 50
isohrstart = 10.0
isohrend = 100.0
isohrstep = 10.0
isohrcustom = False
isohrlist = 
isohrcolor = #000000
isohrlinewidth = 0.5
isohrlinestyle = --
isohrmarker = None
isohrlabel = True
isohrunits = True
isohrposition = 85
isotwbstart = 250.0
isotwbend = 320.0
isotwbstep = 1.0
isotwbcustom = False
isotwblist = 
isotwbcolor = #aa0000
isotwblinewidth = 0.8
isotwblinestyle = :
isotwbmarker = None
isotwblabel = False
isotwbunits = False
isotwbposition = 99
isochorstart = 0.8
isochorend = 1.0
isochorstep = 0.01
isochorcustom = False
isochorlist = 
isochorcolor = #00aa00
isochorlinewidth = 0.8
isochorlinestyle = :
isochormarker = None
isochorlabel = True
isochorunits = False
isochorposition = 90
chart = True

