#This file is automatically generated by the generate_constants_module.py script in dev/scripts.
#DO NOT MODIFY THE CONTENTS OF THIS FILE!
cimport phase_constants_header

iLiquid = phase_constants_header.iLiquid
iSupercritical = phase_constants_header.iSupercritical
iGas = phase_constants_header.iGas
iTwoPhase = phase_constants_header.iTwoPhase
