#This file is automatically generated by the generate_constants_module.py script in dev/scripts.
#DO NOT MODIFY THE CONTENTS OF THIS FILE!

cdef extern from "CoolProp.h":
	enum phase:
		iLiquid
		iSupercritical
		iGas
		iTwoPhase
