#This file is automatically generated by the generate_constants_module.py script in dev/scripts.
#DO NOT MODIFY THE CONTENTS OF THIS FILE!
cimport unit_systems_constants_header

UNIT_SYSTEM_SI = unit_systems_constants_header.UNIT_SYSTEM_SI
UNIT_SYSTEM_KSI = unit_systems_constants_header.UNIT_SYSTEM_KSI
UNIT_SYSTEM_KSI_MOLAR = unit_systems_constants_header.UNIT_SYSTEM_KSI_MOLAR
UNIT_SYSTEM_SI_MOLAR = unit_systems_constants_header.UNIT_SYSTEM_SI_MOLAR
