#This file is automatically generated by the generate_constants_module.py script in dev/scripts.
#DO NOT MODIFY THE CONTENTS OF THIS FILE!

cdef extern from "CoolProp.h":
	enum unit_systems:
		UNIT_SYSTEM_SI
		UNIT_SYSTEM_KSI
		UNIT_SYSTEM_KSI_MOLAR
		UNIT_SYSTEM_SI_MOLAR
