set -o verbose
rm -rf coolprop
git clone --recursive https://github.com/coolprop/coolprop
rm -rf coolprop/.git
cd coolprop/dev
python generate_headers.py
mkdir -p ../build
cd ../build
swig -matlab -c++  -I../../../../include -outcurrentdir ../../../../src/CoolProp.i
cd ../.. #dev/scripts
7z a ../../install_root/MATLAB/swigged_MATLAB_src.7z coolprop

# afterwards in the coolprop/build directory
# cmake .. -DCOOLPROP_MATLAB_SWIGAUTOGENERATED=ON
# cmake --build .