rm -rf coolprop
git clone --recursive https://github.com/coolprop/coolprop
rm -rf coolprop/.git
cd coolprop/dev
python generate_headers.py
mkdir -p ../build
cd ../build
../../swig-matlab/swig-matlab-bin/bin/swig -matlab -c++  -I../../../../include -outcurrentdir ../../../../src/CoolProp.i

# afterwards
cmake .. -DCOOLPROP_MATLAB_SWIGAUTOGENERATED=ON
cmake --build .