#!/usr/bin/env python3
"""Generate include/CoolProp/numerics/cheb2bern_tables.h: exact Chebyshev-to-Bernstein conversion matrices.

For degree n, M[j][k] is the j-th Bernstein coefficient (degree n, on u in [-1, 1], t = (u + 1) / 2) of the
Chebyshev polynomial T_k(u).  Entries are computed exactly in rational arithmetic and rounded once to the
nearest double, so the only error in a conversion b = M c is the rounding of the matrix-vector product.

    python3 dev/scripts/gen_cheb2bern.py > include/CoolProp/numerics/cheb2bern_tables.h
"""
from fractions import Fraction as Fr
from math import comb

NMAX = 17


def cheb_power_t(k):
    """Exact power-basis coefficients in t of T_k(2t - 1), lowest power first."""
    T0, T1 = [Fr(1)], [Fr(-1), Fr(2)]
    if k == 0:
        return T0
    for _ in range(k - 1):
        # T_{m+1}(u) = 2 u T_m(u) - T_{m-1}(u) with u = 2t - 1
        a = [Fr(0)] * (len(T1) + 1)
        for i, c in enumerate(T1):
            a[i] += -2 * c
            a[i + 1] += 4 * c
        for i, c in enumerate(T0):
            a[i] -= c
        T0, T1 = T1, a
    return T1


def matrix(n):
    M = [[Fr(0)] * (n + 1) for _ in range(n + 1)]
    for k in range(n + 1):
        a = cheb_power_t(k) + [Fr(0)] * (n + 1)
        for j in range(n + 1):
            # power basis -> Bernstein basis: b_j = sum_{i <= j} C(j, i) / C(n, i) a_i
            M[j][k] = sum(Fr(comb(j, i), comb(n, i)) * a[i] for i in range(j + 1))
    return M


out = [
    "// GENERATED by dev/scripts/gen_cheb2bern.py -- do not edit.",
    "// Exact Chebyshev-to-Bernstein conversion matrices, rounded once to the nearest double.",
    "// CHEB2BERN_n[j][k] = j-th Bernstein coefficient (degree n, on [-1, 1]) of T_k.",
    "#pragma once",
    "",
    "namespace CoolProp {",
    "namespace ChebyshevBernstein {",
    "namespace detail {",
    "",
]
for n in range(1, NMAX + 1):
    M = matrix(n)
    mx = max(abs(float(v)) for row in M for v in row)
    out.append(f"// degree {n}: max |entry| = {mx:.6g}")
    out.append(f"inline constexpr double CHEB2BERN_{n}[{n + 1}][{n + 1}] = {{")
    for row in M:
        out.append("  {" + ", ".join(repr(float(v)) for v in row) + "},")
    out.append("};")
    out.append("")
out += ["}  // namespace detail", "}  // namespace ChebyshevBernstein", "}  // namespace CoolProp", ""]
print("\n".join(out))
