#!/usr/bin/env python3
"""Emit exact (rational -> nearest double) Chebyshev-to-Bernstein conversion matrices.
B[j][k] = j-th Bernstein coefficient (degree n, on u in [-1,1], t=(u+1)/2) of T_k(u)."""
from fractions import Fraction as Fr
from math import comb
import sys

def cheb_power_t(k):
    """power-basis coefficients in t of T_k(2t-1), exact"""
    T0, T1 = [Fr(1)], [Fr(-1), Fr(2)]
    if k == 0: return T0
    for _ in range(k - 1):
        # T_{m+1} = 2(2t-1) T_m - T_{m-1}
        a = [Fr(0)] * (len(T1) + 1)
        for i, c in enumerate(T1):
            a[i] += -2 * c
            a[i + 1] += 4 * c
        for i, c in enumerate(T0): a[i] -= c
        T0, T1 = T1, a
    return T1

out = ["// generated by gen_cheb2bern.py -- exact rationals rounded to double", "#pragma once"]
for n in map(int, sys.argv[1:]):
    M = [[Fr(0)] * (n + 1) for _ in range(n + 1)]
    for k in range(n + 1):
        a = cheb_power_t(k) + [Fr(0)] * (n + 1)
        for j in range(n + 1):
            M[j][k] = sum(Fr(comb(j, i), comb(n, i)) * a[i] for i in range(j + 1))
    mx = max(abs(float(v)) for row in M for v in row)
    out.append(f"// degree {n}: max |entry| = {mx:.3g}")
    out.append(f"inline constexpr double CHEB2BERN_{n}[{n + 1}][{n + 1}] = {{")
    for row in M:
        out.append("  {" + ", ".join(repr(float(v)) for v in row) + "},")
    out.append("};")
print("\n".join(out))
