/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum _params {
  iB,
  iT,
  iP,
  iD,
  iC,
  iC0,
  iO,
  iU,
  iH,
  iS,
  iA,
  iG,
  iQ,
  iV,
  iL,
  iI,
  iMM,
  iTcrit,
  iTtriple,
  iTreduce,
  iPtriple,
  iPcrit,
  iRhocrit,
  iRhoreduce,
  iAccentric,
  iDpdT,
  iDrhodT_p,
  iTmin,
  iDipole,
  iPhase,
  iPHASE_LIQUID,
  iPHASE_GAS,
  iPHASE_SUPERCRITICAL,
  iPHASE_TWOPHASE,
  iODP,
  iGWP20,
  iGWP100,
  iGWP500,
  iCritSplineT,
  iHcrit,
  iScrit
}
