/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum unit_systems {
  UNIT_SYSTEM_SI,
  UNIT_SYSTEM_KSI,
  UNIT_SYSTEM_KSI_MOLAR,
  UNIT_SYSTEM_SI_MOLAR
}
