/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum unit_constants {
  UNIT_KPA,
  UNIT_PA,
  UNIT_BAR,
  UNIT_KG_M3,
  UNIT_KG_L
}
