name: docs
dependencies:
  - python
  - scipy
  - numpy
  - matplotlib
  - ipython
  - pandas
  - pip
  - six
  - requests
  - jinja2
  - pyyaml
  - packaging
  - pip:
    - cython
    - sphinx
    - sphinxcontrib-napoleon
    - sphinxcontrib-doxylink
    - sphinxcontrib-bibtex
    - cloud_sptheme
    - openpyxl
    - pybtex
    - pickleshare
    - nbsphinx

