SLAVEDIR=/home/buildbot/slavedir
MASTERHOST=bots.coolprop.org:port
SLAVENAME=slavename
SLAVEPASSWORD=pass
BOTADMIN=Author Name
BOTEMAIL=noreply@coolprop.org
BOTHOST=A short description of the host computer
